name: Daily Stock Scraper

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: sudo apt-get update && sudo apt-get install -y google-chrome-stable
    - run: pip install -r requirements.txt
    - run: python scraper.py
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
